#!/usr/bin/env python
from setup_utils import *
import os

# authn_db
def undeploy():
    app = actions.getAppName("authn_db.ear")
    if app: actions.undeploy(app) 
    app = actions.getAppName("authn_db")
    if app: actions.undeploy(app)
    actions.unregisterDB("authn_db")
    
actions, options, arg = getActions()
props = actions.getGlassfish("authn_db-setup.properties", ["dbProperties", "glassfish", "driver", "port"])

prop_name = "authn_db.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()
    
if arg == "INSTALL":
    icatProperties = actions.getProperties(prop_name, prop_list)       
    actions.installFile(prop_name)
    
    try:
        undeploy()
        actions.registerDB(props["driver"], props["dbProperties"], "authn_db")
        actions.deploy("authn_db-*.war", deploymentorder=80)
        app = actions.getAppName("icat.server")
        if app: actions.restartApp(app)
                    
    except Exception, e:
        abort(str(e))
               
if arg == "UNINSTALL":
    actions.removeFile(prop_name)
    try:
        undeploy()
    except Exception, e:
        abort(str(e))       
    
            
    
